- g++.pri
gcc 5.2.1 otherwise complains about:
cc1plus: warning: -Wformat-security ignored without -Wformat [-Wformat-security]
> Fixed incomplete usage of -Wformat-security

- unittests/wsdl_document/test_wsdl_document.cpp
Getting just these two with Qt 5.4.2 on Debian 'stretch'. Same
as the comment suggests for Mac OS X. Question is which system/Qt
combination had 3 errors.
(This is a rather lame solution and more of a bug report than a bugfix. If the results are really that unportable the check might be easier to dumb down the check and make it just check presence
of 1-2 mandatory errors)
> Make the SSL error test pass with yet another signal variation.

- src/KDSoapServer/CMakeLists.txt
- src/KDSoapServer/KDSoapServerCustomVerbRequestInterface.cpp
- src/KDSoapServer/KDSoapServerCustomVerbRequestInterface.h
- src/KDSoapServer/KDSoapServerSocket.cpp
- unittests/servertest/servertest.cpp
modify KDSoapServerObjectInterface to add a new method to handle custom requests
modify KDSoapServerSocket to not reply when custom requests are handled
I am developping a library based on Qt5 and KDSoap to handle UPnP (https://gitlab.com/homeautomationqt/upnp-player-qt). In order to handle http and soap I am using KDSoap server and client implementations.
> add the possibility to handle custom HTTP requests

- doc/CHANGES_1_5.txt
- src/KDSoapClient/CMakeLists.txt
- src/KDSoapClient/KDSoapClient.pro
- src/KDSoapClient/KDSoapClientInterface.h
- src/KDSoapClient/KDSoapEndpointReference.cpp
- src/KDSoapClient/KDSoapEndpointReference.h
- src/KDSoapClient/KDSoapMessage.cpp
- src/KDSoapClient/KDSoapMessage.h
- src/KDSoapClient/KDSoapMessageAddressingProperties.cpp
- src/KDSoapClient/KDSoapMessageAddressingProperties.h
- src/KDSoapClient/KDSoapMessageWriter.cpp
- src/KDSoapClient/KDSoapNamespaceManager.cpp
- src/KDSoapClient/KDSoapNamespaceManager.h
- src/KDSoapClient/KDSoapNamespacePrefixes.cpp
- src/KDSoapClient/KDSoapNamespacePrefixes_p.h
- unittests/CMakeLists.txt
- unittests/unittests.pro
- unittests/ws_addressing_support/CMakeLists.txt
- unittests/ws_addressing_support/ws_addressing_support.pro
- unittests/ws_addressing_support/wsaddressing.wsdl
- unittests/ws_addressing_support/wsaddressingtest.cpp
The ws addressing feature is about setting endpoint and other metadata
into the soap header.
We setup a test wsaddressingtest to cover the direct KDSoapClientInterface API
and will extend it to WSDL generation when needed.
KDSoapClient has a new  abstraction class for ws addressing : KDSoapMessageAddressingProperties
which is a simple layer carrying header soap information. KDSoap message is holding a KDSoapMessageAddressingProperties
that is used when writing the soap envelope Futur patch will use this api to generate addressing properties from WSDL file.
Adding KDSoapEndpointReference to KDSoapClient
References :
http://www.w3.org/TR/ws-addr-core/
http://www.w3.org/TR/ws-addr-soap/
http://www.w3.org/TR/ws-addr-wsdl/
> WS Addressing Support

- variables.pri
Currently the dylib id uses just the library file name:
```
$ otool -L /Users/.../install/lib/libkdsoap.1.dylib
/Users/.../install/lib/libkdsoap.1.dylib:
libkdsoap.1.dylib (compatibility version 1.6.0, current version 1.6.50)
```
After this patch it is prefixed with @rpath
> OS X: Use @rpath in installed dylib id

- src/KDSoapServer/KDSoapServerObjectInterface.cpp
During the release build the `Q_ASSERT` will be removed which leads to the warning `local variable is initialized but not referenced`.
> removed warning during release build

- kdwsdl2cpp/src/converter.cpp
- kdwsdl2cpp/src/main.cpp
- kdwsdl2cpp/src/settings.cpp
- kdwsdl2cpp/src/settings.h
- unittests/keep_unused_types/CMakeLists.txt
- unittests/keep_unused_types/keep_unused_types.cpp
- unittests/keep_unused_types/keep_unused_types.pro
- unittests/keep_unused_types/keep_unused_types.wsdl
This is a follow-up to your comment from https://github.com/KDAB/KDSoap/issues/106 : 
"What might be a problem though, with this approach, is the code that strips out any data structures that aren't used by the WSDL. See Converter::cleanupUnusedTypes. If you add a command-line option for kdwsdl2cpp to keep unused types (by skipping the call to cleanupUnusedTypes when that new option --keep-unused-types is set), I can merge that in."
> Add a -keep-ununsed-types argument to kdwsdl2cpp

- src/KDSoapClient/KDSoapJob.cpp
- src/KDSoapClient/KDSoapJob.h
In some cases it might be necessary to access the KDSoapJob object after the work is done. Since the job deletes itself, this is currently not possible. I've implemented a new setter method to change this behavior (setAutoDelete). Maybe it could be also helpful to have a constructor parameter for this property. This would necessitate taking this parameter into all automatically generated subclasses.
> add configurable auto-deletion of jobs

- KDSoapMacros.cmake
Added KDSOAP_KDWSDL2CPP_COMPILER cmake variable for overriding the
selected kdwsdl2cpp executable. This is useful for cross-compiling,
where a build executable can't be executed by the host (for example,
building an Android application).
> kdwsdl2cpp: Added cmake option for overriding executable path

- src/KDSoapServer/KDSoapServerSocket_p.h
The compilation of KDSoap was failing if Qt is build without SSL
enabled. The define QT_NO_OPENSSL is set in the
QtNetwork/qtnetwork-config.h header, which is not included before the
define is used. QTcpSocket will load header for us and was already
always included (either directly or via QSslSocket).
> KDSoapServer: Fix for Qt without SSL compiled in

- kdwsdl2cpp/src/main.cpp
- kdwsdl2cpp/src/settings.cpp
- kdwsdl2cpp/src/settings.h
- kdwsdl2cpp/src/typemap.cpp
Added -help-on-missing option  to kdwsdl2cpp to display extra help on missing types. This what
we talked about in issue #136 before I found out that KDSoap generates server and client stubs anyway when set to generate server stubs.
> Added -help-on-missing option 

- CMakeLists.txt
Commit a387ff19da8166735dd69edbec1478754f8afe41 enables C++11 support, but by doing so also bumps the required CMake version to 3.1. This prevents building of KDSoap on CentOS/RHEL 7, which is still using CMake 2.8.12.
This PR adds a fall-back way of enabling C++11 for gcc with CMake < 3.1, and relaxes the required CMake version.
> Re-enable support for CMake older than 3.1

- kdwsdl2cpp/schema/parser.cpp
E.g. allow the type name "xs:string " to work. For when you can't fix the source WSDL.
> Fix if a referenced type name has an extra space on the ends. 

- src/KDSoapClient/KDSoapMessageAddressingProperties.cpp
- src/KDSoapClient/KDSoapMessageAddressingProperties.h
- src/KDSoapClient/KDSoapMessageReader.cpp
- src/KDSoapClient/KDSoapNamespaceManager.cpp
- src/KDSoapClient/KDSoapNamespaceManager.h
- unittests/ws_addressing_support/wsaddressingtest.cpp
This pull request adds support for reading WS-Addressing headers for incoming messages. The WS-Addressing headers are placed in KDSoapMessageAddressingProperties, so that the application can use them easily.
It also has a patch for the WS-Addressing writer which doesn't requires destination and source as the [spec](https://www.w3.org/TR/2006/REC-ws-addr-core-20060509/) says they are optional.
> WS-Addressing reader

- kdwsdl2cpp/src/main.cpp
**call:** `kdwsdl2cpp.exe "%TEMP%\test.wsdl" -both "%TEMP%\QwsTestServerBase"`
**error:** `Can't open 'C:/Users/User/AppData/Local/Temp//C:\Users\User\AppData\Local\Temp\QwsTestServerBase.h' for writing.`
**cause:** the header and impl filenames expect only the name without path but the `baseFile` variable contained the full path
> fix absolute path usage with -both

- doc/CHANGES_1_8.txt
- src/KDSoapClient/KDSoapAuthentication.cpp
- src/KDSoapClient/KDSoapAuthentication.h
- src/KDSoapClient/KDSoapClientInterface.cpp
- src/KDSoapClient/KDSoapMessageWriter.cpp
- src/KDSoapClient/KDSoapMessageWriter_p.h
- src/KDSoapClient/KDSoapNamespaceManager.cpp
- src/KDSoapClient/KDSoapNamespaceManager.h
- unittests/CMakeLists.txt
- unittests/dwservice_12_wsdl/test_dwservice_12_wsdl.cpp
- unittests/dwservice_combined_wsdl/test_dwservice_combined_wsdl.cpp
- unittests/dwservice_wsdl/test_dwservice_wsdl.cpp
- unittests/encapsecurity/test_encapsecurity.cpp
- unittests/groupwise_wsdl/test_groupwise_wsdl.cpp
- unittests/import_definition/test_import_definition.cpp
- unittests/literal_true_false/test_literal.cpp
- unittests/msexchange_noservice_wsdl/msexchange_noservice_wsdl.cpp
- unittests/msexchange_wsdl/msexchange_wsdl.cpp
- unittests/salesforce_wsdl/salesforce_wsdl.cpp
- unittests/unittests.pro
- unittests/unqualified_formdefault/test_unqualified.cpp
- unittests/webcalls_wsdl/webcalls_wsdl.cpp
- unittests/ws_usernametoken_support/CMakeLists.txt
- unittests/ws_usernametoken_support/ws_usernametoken_support.pro
- unittests/ws_usernametoken_support/wsusernametoken.wsdl
- unittests/ws_usernametoken_support/wsusernametokentest.cpp
This pull request has some cleanup commits and adds support for WS-UsernameToken. WS-UsernameToken is enabled by setting KDSoapAuthentication::useWSUsernameToken, then a fresh authentication header is added to all requests.
For the unit-test I added KDSoapAuthentication::setOverrideWSUsernameCreatedTime and KDSoapAuthentication::setOverrideWSUsernameNonce to make it reproducible. Do you know a better way of handling this? I think that this way is OK, but it doesn't feel right.
Is it possible to make this feature detectable from CMake, so that my application can fallback to its own implementation for older versions of KDSoap? I am thinking of a CMake variable or version number bump. I don't know what the standard way of doing this is.
> WS-UsernameToken

- kdwsdl2cpp/src/compiler.cpp
- kdwsdl2cpp/src/converter_complextype.cpp
- kdwsdl2cpp/src/creator.cpp
- unittests/optionaltype_regular/test.wsdl
- unittests/optionaltype_regular/testregularapi.cpp
- unittests/optionaltype_regular/testregularapi.h
This now works for polymorphic classes as well. Tests have also been expanded for this.  Change the default name of the argument passed to the setter function. (Fix for _daylight and _timezone i MSVC-2017).
Revert the change in location of the "KODE::setDefaultIndentation" (use of .indent() and .unindent() before calling this will use the old indentation size).
> Generate "hasValueFor{Value}" functions

- doc/CHANGES_1_8.txt
- kdwsdl2cpp/wsdl/definitions.cpp
- unittests/CMakeLists.txt
- unittests/ws_discovery_wsdl/CMakeLists.txt
- unittests/ws_discovery_wsdl/schemas.xmlsoap.org/ws/2004/08/addressing
- unittests/ws_discovery_wsdl/schemas.xmlsoap.org/ws/2005/04/discovery/ws-discovery.xsd
- unittests/ws_discovery_wsdl/test_ws_discovery_wsdl.cpp
- unittests/ws_discovery_wsdl/ws_discovery200504.wsdl
- unittests/ws_discovery_wsdl/ws_discovery_wsdl.pro
Added support for generating messages for WSDL files without
services or bindings. Mainly to support WS-Discovery WSDL.
In an effort to create a [WS-Discovery client library](https://gitlab.com/caspermeijn/kdsoap-ws-discovery-client) I needed this change to generate the needed messages.
> Allow generating message without service or bindings

- doc/CHANGES_1_8.txt
- kdwsdl2cpp/src/converter_clientstub.cpp
- kdwsdl2cpp/src/converter_complextype.cpp
- kdwsdl2cpp/src/converter_simpletype.cpp
- kdwsdl2cpp/src/elementargumentserializer.cpp
- kdwsdl2cpp/src/typemap.cpp
- kdwsdl2cpp/src/typemap.h
- src/KDSoapClient/CMakeLists.txt
- src/KDSoapClient/KDQName.cpp
- src/KDSoapClient/KDQName.h
- src/KDSoapClient/KDSoapMessageReader.cpp
- src/KDSoapClient/KDSoapValue.cpp
- src/KDSoapClient/KDSoapValue.h
- unittests/empty_list_wsdl/empty_list_wsdl.cpp
- unittests/enum_escape/test_enum.cpp
- unittests/ws_discovery_wsdl/test_ws_discovery_wsdl.cpp
- unittests/wsdl_document/test_wsdl_document.cpp
These change add support for sending and receiving qnames. It adds a new KDQName class, this is used to represent the xml qname and the reader and writer are extended to support it.
I am not sure whether this will break existing code, as the soap qname are now represented as KDQName instead of QString. But qnames couldn't be fully used in the past, as the xml namespaces were not correctly passed to the reader/writer.
I am not sure whether this is the simplest solution. I am open for suggestion for simplifying it.
> Support qname

- kdwsdl2cpp/CMakeLists.txt
- kdwsdl2cpp/src/converter_simpletype.cpp
- unittests/CMakeLists.txt
- unittests/list_restriction/CMakeLists.txt
- unittests/list_restriction/test_list_restriction.cpp
- unittests/unittests.pro
For schema:
```xml
<xsd:simpleType name=dArrayType>
<xsd:list itemType=xsd:double/>
</xsd:simpleType>
<xsd:simpleType name=d3ArrayType>
<xsd:restriction base=test:dArrayType>
<xsd:length value=3/>
</xsd:restriction>
</xsd:simpleType>
```
when generating code, `kdwsdl2cpp` skips the call to the `entries()` method for `DArrayType`.
For example, `void D3ArrayType::setValue (const DArrayType & value)` instead of `"value.entries().length ()"` is generated by `"value.length()"`
```c++
void D3ArrayType::setValue( const DArrayType& value )
{
bool rangeOk = true;
rangeOk = rangeOk && (value.length() == 3);
if (!rangeOk)
qDebug( "Invalid range in D3ArrayType::setValue()" );
mValue = value;
}
```
> List restriction to base

- doc/CHANGES_1_8.txt
- src/KDSoapClient/KDDateTime.cpp
- src/KDSoapClient/KDDateTime.h
- unittests/CMakeLists.txt
- unittests/kddatetime/CMakeLists.txt
- unittests/kddatetime/kddatetime.cpp
- unittests/kddatetime/kddatetime.pro
- unittests/unittests.pro
This prevents the QVariant from being implicitly constructed using the base QDateTime, which leads to the loss of information (#123).
> KDDateTime: added a QVariant conversion operator

- kdwsdl2cpp/schema/parser.h
- src/KDSoapServer/KDSoapServerObjectInterface.h
As described in https://github.com/KDAB/KDSoap/issues/171
Moved this single commit to a different branch just to make the request a bit cleaner.
> Fixed ambiguous class name error with Qt custom namespace.

- kdwsdl2cpp/src/converter_complextype.cpp
- unittests/CMakeLists.txt
- unittests/QSharedPointer_include/CMakeLists.txt
- unittests/QSharedPointer_include/QSharedPointer_include.pro
- unittests/QSharedPointer_include/test_qsharedpointer_include.cpp
- unittests/QSharedPointer_include/test_qsharedpointer_include_wsdl.wsdl
- unittests/unittests.pro
The error is that when generating code, the inclusion of `<QSharedPointer>` occurs in `code_from_wsdl.cpp`, and not in `code_from_wsdl.h`
> compiled error when wsdl code generated

- CMakeLists.txt
- doc/CHANGES_1_9.txt
- examples/helloworld_server/helloworld_server.h
- examples/helloworld_server/main.cpp
- kdwsdl2cpp/libkode/function.h
- kdwsdl2cpp/libkode/printer.cpp
- kdwsdl2cpp/schema/complextype.h
- kdwsdl2cpp/src/converter_clientstub.cpp
- kdwsdl2cpp/src/converter_complextype.cpp
- kdwsdl2cpp/src/converter_serverstub.cpp
- kdwsdl2cpp/wsdl/soapbinding.h
- src/KDSoapClient/KDSoapClientThread_p.h
- src/KDSoapServer/KDSoapServer.h
- src/KDSoapServer/KDSoapServerThread_p.h
- testtools/httpserver_p.cpp
- testtools/httpserver_p.h
- unittests/ihc_wsdl/test_ihc.cpp
- unittests/prefix_wsdl/test_prefix.cpp
- unittests/servertest/servertest.cpp
- unittests/tech3356_wsdl/test_tech3356.cpp
- unittests/wsdl_document/test_wsdl_document.cpp
- unittests/wsdl_rpc-server/test_wsdl_rpc_server.cpp
This adds the c++11 override indicator (1) to the library code, (2) to the generated code and (3) enables warnings for missing indicators.
The library is already dependent on c++11, so commit 1 is not a problem. However I am not sure whether the generated code is already dependant on c++11 and whether this would be a problem (commit 2). The third commit enables a warning in CMake, I am not sure whether this is the correct way to do that.
I want this change as recent compilers will show a lot of warning for the generated code of the ONVIF wsdl.
> Add c++11 override indicator

- doc/CHANGES_1_9.txt
- src/KDSoapClient/KDSoapMessageAddressingProperties.cpp
- src/KDSoapClient/KDSoapMessageAddressingProperties.h
- src/KDSoapClient/KDSoapMessageWriter.cpp
- src/KDSoapClient/KDSoapNamespacePrefixes.cpp
- src/KDSoapClient/KDSoapNamespacePrefixes_p.h
- unittests/ws_addressing_support/wsaddressingtest.cpp
This adds the option to select the namespace used when sending
WS-Addressing messages. This is needed because the WS-Discovery spec
explicitly mentions the WS-Addressing 2004-08 namespace and some devices
will only respond to messages using that specific namespace.
Tested with [kdsoap-ws-discovery-client](https://gitlab.com/caspermeijn/kdsoap-ws-discovery-client) and [wsdd](https://github.com/KoynovStas/wsdd).
> addressing: Add namespace selection

- .gitignore
Extended .gitignore to ignore the generated files on a Linux cmake build properly.
> Extendend gitignore

- kdwsdl2cpp/common/fileprovider.cpp
- kdwsdl2cpp/src/main.cpp
- kdwsdl2cpp/src/settings.cpp
- kdwsdl2cpp/src/settings.h
I needed to interact with a web service protected with PKCS12 based certificate.
To parse the WSDL files from these servers I added two command line arguments to the kdwsdl2cpp to being able to load a certificate file.
Ps. because the QSslCertificate::importPkcs12 is only supported above Qt 5.4 and newer I have added guards around the new functionality.
@dfaure-kdab , @caspermeijn this is the same modification what I have submitted in PR #187 (plus the David requested warning in the help), but somehow I cannot amend and push it anymore (it shows an unknown repository as  source):
> [kdwsdl2cpp]Add option for loading PKCS12 certificates

- doc/CHANGES_1_9.txt
- src/KDSoapClient/CMakeLists.txt
- src/KDSoapClient/KDSoapMessage.h
- src/KDSoapClient/KDSoapUdpClient.cpp
- src/KDSoapClient/KDSoapUdpClient.h
- src/KDSoapClient/KDSoapUdpClient_p.h
- unittests/CMakeLists.txt
- unittests/soap_over_udp/CMakeLists.txt
- unittests/soap_over_udp/docs.oasis-open.org/ws-dd/discovery/1.1/os/wsdd-discovery-1.1-schema-os.xsd
- unittests/soap_over_udp/test_soap_over_udp.cpp
- unittests/soap_over_udp/wsdd-discovery-200901.wsdl
- unittests/soap_over_udp/www.w3.org/2006/03/addressing/ws-addr.xsd
KDSoapUdpClient provides an interface for implementing a
SOAP-over-UDP[1] client.
It includes tests and documentation. I tested it with (kdsoap-ws-discovery-client)[https://gitlab.com/caspermeijn/kdsoap-ws-discovery-client].
Fixes #175 
[1] https://docs.oasis-open.org/ws-dd/soapoverudp/1.1/os/wsdd-soapoverudp-1.1-spec-os.html
> KDSoapUdpClient

- src/KDSoapClient/KDSoapClient.pro
- src/KDSoapClient/KDSoapUdpClient_p.h
- unittests/soap_over_udp/soap_over_udp.pro
- unittests/unittests.pro
was missing in e0a3bbce1e527f3a5734adb66628b264176faf70 which introduced
soap over udp but neglected to add it to qmake
> add qmake support for soap over udp

- src/KDSoapClient/KDSoapMessageAddressingProperties.cpp
- unittests/ws_addressing_support/wsaddressingtest.cpp
as per https://www.w3.org/Submission/ws-addressing/ the only well-known
uri in 2004/08 was anonymous and it has a role prefix. from the
implicit reading I can find on earlier versions the same applies to them.
so, when constructing the well-known URIs inject a role prefix when
dealing with specs up to 2004/08 and raise a warning when attempting to
use anything but anonymous
same for /id/unspecified
(recreates #180 which broke for reasons :flushed:)
> fix spec compliance

- src/KDSoapClient/CMakeLists.txt
- src/KDSoapServer/CMakeLists.txt
the cmake package gets imported targets generated for use by API consumers.
so they can do
```
target_link_libraries(myapp KDSoap::kdsoap)
```
in their cmake code and because KDSoap::kdsoap is an imported target cmake
automatically knows where to find the library. alas, since we didn't
set an interface directory cmake did not know where to find the relevant
headers.
this isn't a problem so long as they are in one of the standard search
paths (e.g. /usr/include), but when the are installed elsewhere (e.g.
/opt/kdsoap/include) they will not be found.
by explicitly setting the INSTALL_INTERFACE to INSTALL_INCLUDE_DIR the
generated KDSoapTargets.cmake will set the relevant path on the target
and thus allow idiomatic use of the imported target without having to
mess with include dirs manually.
> set the cmake install interface directories on the library targets

- kdwsdl2cpp/libkode/printer.cpp
- kdwsdl2cpp/libkode/printer.h
Mainly useful when tweaking kdwsdl2cpp because the generated files not
gooing to be modified if their contents did not changed. This could
reduce the compilation time of the projects including the generated
codes.
This change have been manually copied over from the kode's libkode where
it got reviewed by @dfaure-kdab:
https://github.com/cornelius/kode/pull/32
> [kdwsdl2cpp]Do not overwrite output files in the case their content unchanged

- kdwsdl2cpp/src/typemap.cpp
> correct c++ syntax for localTypeForElement

- kdwsdl2cpp/src/kdwsdl2cpp.pro
- kdwsdl2cpp/src/kdwsdl2cpp_lib.pro
- unittests/unittests.pri
I have managed to miss the renaming a couple of references in qmake project files to the libkode/libkode -> libkode/code_generation. This PR fixes these references.
> Fix missing libkode -> code_generation renames

- kdwsdl2cpp/src/main.cpp
I got an `Invalid or empty cipher list ()` error when tried to connect to a webservice with PKCS12 certificate. 
This was due to the fact that the PKCS12 extracted  configuration was merged to an empty SSL configuration not to the default, which resulted loosing the available chipers.
> Fix PKCS12 certificate loading

- kdwsdl2cpp/src/converter_clientstub.cpp
Generate includes for the type of the call arguments to the client codes even if only async job based implementation is generated.
Fixes #227
> [kdwsdl2cpp]Fix #227

- KDSoapMacros.cmake
Set SKIP_AUTOUIC to ON for generated files by KDSoap CMake functions.
Just like it's being done in Qt5CoreMacros.cmake from qtbase as well.
Fixes:
```
CMake Warning (dev) in resources/sugarcrm/CMakeLists.txt:
Policy CMP0071 is not set: Let AUTOMOC and AUTOUIC process GENERATED files.
Run "cmake --help-policy CMP0071" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
For compatibility, CMake is excluding the GENERATED source file(s):
".../FatCRM/resources/sugarcrm/wsdl_sugar41.h"
".../FatCRM/resources/sugarcrm/wsdl_sugar41.cpp"
```
> Fix CMake warnings

- .gitignore
The directory is suggested here but not ignored by git..
https://github.com/KDAB/KDSoap/blob/dc4754f03aebb3201e61742c515df808f77471e6/INSTALL.txt#L19-L25
> ignore CMake build folder

- src/KDSoapClient/KDSoapClientInterface.cpp
- src/KDSoapClient/KDSoapClientInterface.h
- src/KDSoapClient/KDSoapClientInterface_p.h
- src/KDSoapClient/KDSoapClientThread.cpp
- testtools/httpserver_p.cpp
- testtools/httpserver_p.h
- unittests/builtinhttp/builtinhttp.cpp
If this option is enabled the action parameter (which is passed as an
url parameter by the current implementation) will be put to the message
header. 
I have tested it with a SOAP master implementation written in .NET.
> Add support for WS:Addressing in KDSoapClient

- src/KDSoapClient/KDQName.h
This is needed with Qt 6, if the operator is externally visible it is also assumed to be exported, causing linker errors in consumer code otherwise.
The alternative approach would be to remove the declaration from the header file entirely.
> Export KDQName debug stream operator

- kdwsdl2cpp/src/converter.h
- kdwsdl2cpp/src/converter_serverstub.cpp
If the WSDL file contains more than 122 functions, the code generated by kdwsdl2cpp throws compiler error C1061 (MSVC). This is caused by the huge if statement in processRequest().
Fixed by replacing else if with if in processRequest().
> Fix compiler error C1061 when using more than 122 functions

- src/KDSoapClient/CMakeLists.txt
- src/KDSoapServer/CMakeLists.txt
Install the Windows pdb files in the bin (or runtime) directory and not into the library dir.
> Install the Windows pdb files in the bin dir

- .github/workflows/build.yml
macOS 12 is deprecated and will soon be removed
> CI update to macOS 13

- .clazy
- .github/workflows/nightly.yml
- .github/workflows/tidyclazy.yml
- CMakePresets.json
Removed .clazy file which was only read by KDAB CI. Moved env variables from nightly.yml to CMakePresets.json, so users can run clazy locally as well.
Adapted nightly.yml to use the preset.
Also 2 whitespace changes which I only noticed now, done by editor on save.
> Don't set clazy settings in multiple places

- .github/workflows/tidyclazy.yml
- CMakeLists.txt
It requires
CMAKE_EXPORT_COMPILE_COMMANDS=ON
which is enabled on base preset.
> Add cppcheck target and call it on CI

- docs/CHANGES_2_3.txt
- src/KDSoapServer/KDSoapServerSocket.cpp
- unittests/serverlib/test_serverlib.cpp
Make sure we never go outside the base directory
Fixes #314
> Improve security when handling requests to download files

- kdwsdl2cpp/src/compiler.cpp
- kdwsdl2cpp/src/converter_clientstub.cpp
- kdwsdl2cpp/wsdl/definitions.cpp
- src/KDSoapClient/KDDateTime.cpp
- src/KDSoapClient/KDSoapMessageAddressingProperties.cpp
- src/KDSoapClient/KDSoapMessageReader.cpp
- src/KDSoapClient/KDSoapValue.cpp
- testtools/httpserver_p.cpp
- unittests/CMakeLists.txt
- unittests/kddatetime/test_kddatetime.cpp
- unittests/kdwsdl2cpp_jobs/CMakeLists.txt
- unittests/kdwsdl2cpp_jobs/jobs.wsdl
- unittests/kdwsdl2cpp_jobs/test_jobs.cpp
- unittests/ws_usernametoken_support/test_wsusernametoken.cpp
Create classes for SOAP OneWayOperations, fixes #311
Additionally don't use deprecated Qt features - should be able to compile KDSoap with QT_DISABLE_DEPRECATED_BEFORE=0x060900 / QT_DISABLE_DEPRECATED_UP_TO=0x060900.
libkode still uses one deprecated function in  schema/parser.cpp
> Create jobs for soap one way operations with kdwsdl2cpp

- kdwsdl2cpp/src/main.cpp
I was bored. @dfaure-kdab you only have yourself to blame for this pull request:
https://github.com/KDAB/KDSoap/issues/224#issuecomment-664620674
> Switch to QCommandLineParser.

- src/KDSoapServer/KDSoapServerObjectInterface.cpp
- src/KDSoapServer/KDSoapServerObjectInterface.h
- src/KDSoapServer/KDSoapServerSocket.cpp
- src/KDSoapServer/KDSoapServerSocket_p.h
- unittests/serverlib/test_serverlib.cpp
I've been sitting on this patch for 9 years.
Essentially no matter the incoming version of the SOAP request to KDSoapServer, it always replies with a SOAP 1.1 message body.
This stores the incoming SOAP version to ensure the reply uses the correct SOAP version.
I'll look at doing some unit tests for it, although after nearly a decade I know it works.
> Use correct version for SOAP replies.

- src/KDSoapServer/KDSoapServerObjectInterface.cpp
- src/KDSoapServer/KDSoapServerSocket.cpp
- src/KDSoapServer/KDSoapServerSocket_p.h
- unittests/CMakeLists.txt
- unittests/ranges/CMakeLists.txt
- unittests/ranges/test_ranges.cpp
This pull request adds support for HTTP range requests to handleFileDownload.
Range requests allow a client to request only a portion of a file to be transferred. What I actually use this for is for transferring data or log files which grow over time, rather than retreiving the whole file every time, this allows the client to resume the download.
If you're happy to add support for range requests I'll write some unit tests.
> Support for RFC 7233 (Range Requests).
